<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSc2nx9u\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSc2nx9u/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSc2nx9u.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSc2nx9u\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSc2nx9u\appProdProjectContainer(array(
    'container.build_hash' => 'Sc2nx9u',
    'container.build_id' => '20efd74a',
    'container.build_time' => 1521388578,
));
