<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5z8r05f\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5z8r05f/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5z8r05f.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5z8r05f\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5z8r05f\appDevDebugProjectContainer(array(
    'container.build_hash' => '5z8r05f',
    'container.build_id' => '47a2513d',
    'container.build_time' => 1527450752,
));
